page_gen-dirs: true # uncomment, if you prefer to generate named folders
theme: "just-the-docs"
title: BSML Docs
description: Documentation for Beat Saber library BeatSaberMarkupLanguage
logo: "/assets/images/logo.png"
search_enabled: true
heading_anchors: true
footer_content: "Copyright &copy; 2019 David L. Distributed by an <a href=\"https://github.com/monkeymanboy/BeatSaberMarkupLanguage/blob/master/LICENSE\">MIT license.</a>"
baseurl: "/BSML-Docs"
url: "https://monkeymanboy.github.io"
aux_links:
  "GitHub":
    - "//github.com/monkeymanboy/BeatSaberMarkupLanguage"
page_gen:
  - data: 'TypeHandlers'
    template: 'TypeHandler'
    name: 'type'
    dir: 'TypeHandlers'
  - data: 'Tags'
    template: 'Tag'
    name: 'type'
    dir: 'Tags'
  - data: 'Macros'
    template: 'Macro'
    name: 'type'
    dir: 'Macros'